'use strict';
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const KEY='cau-noi-khong-gian-v2', SETKEY='cau-noi-khong-gian-v1-settings';
const freshLevel=()=>({started:false,nodes:[],bestScore:0,bestCost:null,bestDesign:null,solved:[false,false,false,false],times:[90,90,90,90],energy:100,credits:100,score:0,hints:3,correct:0,edges:[],history:[],fails:0,wrong:0,stars:0,complete:false,powers:{heal:false,time:false,scan:false,boost:false}});
const freshSave=()=>({name:'',avatar:0,unlocked:0,last:0,levels:Array.from({length:6},freshLevel)});
let teacherAuthorized=false;
const TEACHER_PASSWORD='05067379';
let save=freshSave(),settings={volume:.35,muted:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,timer:90};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&s.levels?.length===6&&s.levels.every(x=>Array.isArray(x.edges)&&x.powers))save=s;const c=JSON.parse(localStorage.getItem(SETKEY));if(c)settings={...settings,...c};}catch(e){}
try{if(!localStorage.getItem(KEY)){const old=JSON.parse(localStorage.getItem('cau-noi-khong-gian-v1'));if(old?.levels?.length===6){save.name=old.name||'';save.avatar=old.avatar||0;save.unlocked=old.unlocked||0;save.last=old.last||0;old.levels.forEach((l,i)=>{const n=save.levels[i];for(const key of ['solved','times','energy','score','hints','correct','wrong','started'])if(l[key]!==undefined)n[key]=l[key];n.credits=100+180*n.solved.filter(Boolean).length;});}}}catch(e){}
let levelIndex=0,level=null,teacherTest=false,tool='road',selectedNode=null,dragFrom=null,dragPoint=null,running=null,quiz=null,modalKind='',scanUntil=0,flashUntil=0,lastFrame=0,toastId,teacherIndex=0,lastSimulation=null,failedState=null,pointerStart=null,hoverPoint=null;
const COLORS=['#65e6c4','#c4a1ff','#ffbc80'];
function persist(){if(!teacherTest){try{localStorage.setItem(KEY,JSON.stringify(save));}catch(e){toast('Trình duyệt không lưu được. Hãy giữ tab mở để tiếp tục.');}}}
function storeSettings(){try{localStorage.setItem(SETKEY,JSON.stringify(settings));}catch(e){}document.body.classList.toggle('reduce',settings.reduced);if(audio.master)audio.master.gain.value=settings.muted?0:settings.volume;}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(n){return String(n).replace('.',',');}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastId);toastId=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function modal(html,kind){quiz=null;modalKind=kind;$('modalBody').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function closeModal(){teacherAuthorized=false;if(quiz)persist();quiz=null;$('modal').close();modalKind='';}
$('closeModal').onclick=closeModal;$('modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
$('modal').addEventListener('click',e=>{if(e.target===$('modal')&&e.clientX<$('modal').getBoundingClientRect().left)closeModal();});
const audio={ctx:null,master:null,step:0,interval:null,init(){if(!this.ctx){try{this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=settings.muted?0:settings.volume;this.master.connect(this.ctx.destination);this.interval=setInterval(()=>this.music(),240);}catch(e){return;}}this.ctx.resume().catch(()=>{});},tone(freq,duration=.15,type='sine',vol=.1,delay=0){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime+delay;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);},sfx(type){this.init();if(type==='ok'){[440,554,659].forEach((f,i)=>this.tone(f,.3,'sine',.13,i*.1));}else if(type==='fail'){this.tone(120,.3,'triangle',.16);this.tone(90,.3,'triangle',.14,.14);}else if(type==='win'){[392,494,587,784].forEach((f,i)=>this.tone(f,.55,'triangle',.12,i*.14));}else this.tone(type==='build'?340:600,.08,'triangle',.09);},music(){if(!this.ctx||document.hidden||$('game').classList.contains('hidden'))return;const tracks=[[0,4,7,12,7,4,9,7],[0,3,7,10,12,7,3,5],[0,7,11,14,11,7,4,2],[0,2,7,9,14,9,7,2],[0,5,9,12,16,12,9,5],[0,4,7,11,12,16,14,7]],roots=[196,174.61,220,164.81,207.65,146.83];const s=this.step++,m=levelIndex;this.tone(roots[m]*2**(tracks[m][s%8]/12),.48,'sine',quiz?.018:.035);if(s%4===0)this.tone(roots[m]/2,1,'triangle',.05);if(running&&s%2===0)this.tone(55+(s%3)*8,.1,'sawtooth',.018);}};
document.addEventListener('pointerdown',()=>audio.init(),{once:true});
function money(n){return n.toLocaleString('vi-VN',{maximumFractionDigits:1});}
function spent(){return Bridge.cost(level.nodes,level.edges);}
function refreshBudget(){level.credits=Math.max(0,100+180*level.solved.filter(Boolean).length-spent());}
function totalBest(){return save.levels.reduce((s,l)=>s+(l.bestScore||0),0);}
function mapThumb(i){const m=Bridge.terrains[i],path=m.route.map(p=>p.map((v,j)=>j===0?v/3:(v-100)/3));return `<svg viewBox="0 0 400 170" aria-hidden="true"><path d="M0 ${(m.start[1]-100)/3}H${m.start[0]/3}V170H0Z M${m.end[0]/3} ${(m.end[1]-100)/3}H400V170H${m.end[0]/3}Z" fill="#183c48"/>${m.platforms.map(p=>`<rect x="${p.x/3}" y="${(p.y-100)/3}" width="${p.w/3}" height="110" fill="#315665"/>`).join('')}${m.obstacles.map(r=>`<rect x="${r.x/3}" y="${(r.y-100)/3}" width="${r.w/3}" height="${r.h/3}" fill="#846557"/>`).join('')}<path d="${path.map((p,j)=>(j?'L':'M')+p.join(' ')).join(' ')}" fill="none" stroke="${MAPS[i].color}" stroke-width="3" stroke-dasharray="6 5"/>${m.anchors.map(p=>`<circle cx="${p[0]/3}" cy="${(p[1]-100)/3}" r="5" fill="${MAPS[i].color}"/>`).join('')}</svg>`;}
function renderHome(){document.documentElement.style.setProperty('--accent','#65e6c4');$('playerName').value=save.name;$$('[data-avatar]').forEach(b=>b.classList.toggle('selected',+b.dataset.avatar===save.avatar));$('continueBtn').disabled=!save.name&&!save.levels.some(l=>l.solved.some(Boolean));$('totalStars').innerHTML=`<b>${totalBest().toLocaleString('vi-VN')} điểm</b><br><small>★ ${save.levels.reduce((s,l)=>s+l.stars,0)} / 18 · Tổng kỷ lục 6 map</small>`;$('mapCards').innerHTML=MAPS.map((m,i)=>`<button class="mapCard" data-map="${i}" ${i>save.unlocked?'disabled':''} style="--map-color:${m.planet}55"><div class="mapArt">${mapThumb(i)}</div><span class="mapNum">0${i+1}</span><span class="mapLock">${i>save.unlocked?'CHƯA MỞ':save.levels[i].bestScore?'★'.repeat(save.levels[i].stars):'SẴN SÀNG'}</span><div class="mapInfo"><small>${Bridge.terrains[i].label}</small><h3>${m.name}</h3><p>${m.tag}</p><div class="mapRecord">${save.levels[i].bestScore?`${save.levels[i].bestScore} điểm · ${money(save.levels[i].bestCost)} vật liệu`:'Kỷ lục đang chờ bạn'}</div></div></button>`).join('');$$('[data-map]').forEach(b=>b.onclick=()=>startLevel(+b.dataset.map));}
function nodeMenus(){for(const id of ['nodeA','nodeB']){const old=$(id).value;$(id).innerHTML=getNodes().map((n,j)=>`<option value="${j}">${n.label}${n.fixed?' · neo':''}</option>`).join('');if(+old<getNodes().length)$(id).value=old;}if($('nodeA').value===$('nodeB').value)$('nodeB').value='1';}
function initDesign(i){if(!level.nodes?.length){level.nodes=Bridge.setup(i);level.edges=Bridge.freeEdges(i,level.nodes);level.history=[];}refreshBudget();}
function startLevel(i,test=false){if(test&&!teacherAuthorized&&!teacherTest){requestTeacherAccess();return;}audio.init();closeModal();clearTimeout(toastId);$('toast').classList.remove('show');teacherTest=test;levelIndex=i;level=test?freshLevel():save.levels[i];if(test||!level.started)level.times.fill(settings.timer);level.started=true;initDesign(i);if(!test){save.name=$('playerName').value.trim()||save.name||'Kỹ sư';save.last=i;persist();}tool='road';selectedNode=null;running=null;failedState=null;lastSimulation=null;scanUntil=0;$('home').classList.add('hidden');$('game').classList.remove('hidden');$('testBadge').classList.toggle('hidden',!test);$('sampleBtn').classList.toggle('hidden',!test);document.documentElement.style.setProperty('--accent',MAPS[i].color);$('mapTitle').textContent=`0${i+1} / ${MAPS[i].name}`;$('mapDesc').textContent=Bridge.terrains[i].label;$('loadLabel').textContent=`${Bridge.terrains[i].convoy} XE · TẢI ${Bridge.terrains[i].load} / XE`;$('algyText').textContent=Bridge.terrains[i].tip;nodeMenus();update();window.scrollTo(0,0);if(level.energy<=0)gameOver();}
function goHome(){if(running)return toast('Dừng lượt chạy thử trước khi về bản đồ.');if(level&&!teacherTest&&!confirm('Về bản đồ? Bản thiết kế, câu đã làm và thời gian sẽ được lưu.'))return;persist();closeModal();teacherTest=false;level=null;$('game').classList.add('hidden');$('home').classList.remove('hidden');renderHome();window.scrollTo(0,0);}
function resetLevel(){if(!teacherTest){const old=save.levels[levelIndex],n=freshLevel();for(const k of ['bestScore','bestCost','bestDesign','stars'])n[k]=old[k];save.levels[levelIndex]=n;}startLevel(levelIndex,teacherTest);}
$('restartBtn').onclick=()=>{if(!running&&confirm('Làm lại màn từ đầu? Kỷ lục tốt nhất và các màn đã mở vẫn được giữ.'))resetLevel();};$('homeBtn').onclick=goHome;$('brand').onclick=e=>{e.preventDefault();if(!$('game').classList.contains('hidden'))goHome();};$('startBtn').onclick=()=>startLevel(save.unlocked);$('continueBtn').onclick=()=>startLevel(Math.min(save.last,save.unlocked));$('playerName').onchange=()=>{save.name=$('playerName').value.trim();persist();};$$('[data-avatar]').forEach(b=>b.onclick=()=>{save.avatar=+b.dataset.avatar;persist();renderHome();});
function update(){if(!level)return;refreshBudget();const done=level.solved.filter(Boolean).length;$('energyText').textContent=level.energy+' / 100';$('energyBar').style.width=level.energy+'%';$('energyBar').style.background=level.energy<=25?'#ff8c9b':MAPS[levelIndex].color;$('creditsText').textContent=money(level.credits);$('scoreText').textContent=level.score;$('phaseLabel').textContent=running?'ĐANG CHẠY THỬ · THEO DÕI ĐỘ VÕNG':`XƯỞNG TỰ DO · ${done}/4 HỒ SƠ`;
const titles=['Mở mặt đường','Mở hợp kim chịu lực','Mở cáp treo','Hoàn tất kiểm định'];$('missions').innerHTML=level.solved.map((s,i)=>`<button class="mission ${s?'done':''}" data-q="${i}" ${running?'disabled':''}><span class="number">${i+1}</span><span><b>${titles[i]}</b><small>${s?'Đã hoàn thành · xem lại':i===done?'+180 vật liệu · bắt đầu':'Hoàn thành bước trước'}</small></span></button>`).join('');$$('[data-q]').forEach(b=>b.onclick=()=>{const i=+b.dataset.q;if(i>done)return toast('Hãy hoàn thành các hồ sơ theo thứ tự.');openQuiz(i);});
$$('[data-tool]').forEach(b=>{b.classList.toggle('selected',b.dataset.tool===tool);b.disabled=!!running||level.energy<=0||(b.dataset.tool==='road'&&!level.solved[0])||(b.dataset.tool==='steel'&&!level.solved[1])||(b.dataset.tool==='cable'&&!level.solved[2]);});for(const id of ['restartBtn','teacherBtn','settingsBtn','helpBtn','clearBtn','restoreBtn','addNodeBtn','connectBtn','sampleBtn'])$(id).disabled=!!running||level.energy<=0;$('restoreBtn').disabled=!!running||!level.bestDesign;$('runBtn').disabled=!!running||done<4||level.energy<=0;$('stopBtn').classList.toggle('hidden',!running);$('undoBtn').disabled=!!running||!level.history.length||level.energy<=0;for(const p of ['heal','time','scan','boost'])$(p+'Btn').disabled=!!running||level.powers[p]||level.energy<=0||(p==='heal'&&level.energy>=100)||(p==='time'&&done===4);
$('sceneHint').textContent=running?'Xe chạy trên đường bạn xây · Đỏ: thanh đang chịu tải cao':selectedNode!==null?`${getNodes()[selectedNode]?.label||'Điểm'} → chạm điểm mới để nối · Esc để bỏ chọn`:'Nút vàng = neo cố định · Chạm/kéo để nối và tạo điểm · Thanh giao nhau chỉ nối khi có nút';const cost=spent(),award=Bridge.award(cost,400);$('spentText').textContent=money(cost);$('projectedText').textContent=award.total;$('bestText').textContent=level.bestScore||'—';$('allBestText').textContent=totalBest().toLocaleString('vi-VN');$('buildStatus').textContent=done<4?`Còn ${4-done} hồ sơ để mở chạy thử. Được xây dần và thu hồi toàn bộ vật liệu.`:`${level.nodes.length} điểm · ${level.edges.filter(e=>!e.free).length} thanh · Thử lại không trừ điểm.`;}
function getNodes(){return level.nodes;}
function snapshot(){level.history.push({nodes:level.nodes.map(n=>({...n})),edges:level.edges.map(e=>({...e}))});if(level.history.length>80)level.history.shift();}
function changed(){failedState=null;lastSimulation=null;refreshBudget();nodeMenus();persist();update();}
function edgeBetween(a,b){return level.edges.find(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a));}
function addNode(p){const m=Bridge.terrains[levelIndex];if(!Bridge.validPoint(p,m)){toast('Đặt điểm trong vùng xây, bên ngoài khối đá.');return -1;}const found=level.nodes.findIndex(n=>Bridge.length(n,p)<14);if(found>=0)return found;if(level.nodes.length>=40){toast('Tối đa 40 điểm. Hãy xóa điểm thừa để tiếp tục.');return -1;}snapshot();let fixed=false;for(const platform of m.platforms)if(p.x>=platform.x&&p.x<=platform.x+platform.w&&Math.abs(p.y-platform.y)<8){p.y=platform.y;fixed=true;}
const j=level.nodes.length;level.nodes.push({...p,fixed,label:'P'+j}); // Split any member at the new point; intersections otherwise remain unconnected.
const out=[];for(const e of level.edges){const a=level.nodes[e.a],b=level.nodes[e.b],L=Bridge.length(a,b),t=((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/(L*L),dist=Math.abs((p.x-a.x)*(b.y-a.y)-(p.y-a.y)*(b.x-a.x))/L;if(t>.02&&t<.98&&dist<.5){out.push({...e,b:j},{...e,a:j});}else out.push(e);}level.edges=out;changed();return j;}
function snapPoint(p){const n=near(p);if(n>=0)return{x:level.nodes[n].x,y:level.nodes[n].y};if($('snapCheck').checked)return{x:Math.round(p.x/20)*20,y:Math.round(p.y/20)*20};return{x:Math.round(p.x),y:Math.round(p.y)};}
function join(a,b){if(running||!level||level.energy<=0||a===b)return false;const A=level.nodes[a],B=level.nodes[b];if(!A||!B)return false;const e=edgeBetween(a,b);if(tool==='erase'){if(!e)return toast('Chưa có thanh nối hai điểm này.');if(e.free)return toast('Đường trên đảo là địa hình có sẵn.');snapshot();level.edges=level.edges.filter(x=>x!==e);changed();return true;}
if(!Bridge.materials[tool])return false;const unlock={road:0,steel:1,cable:2}[tool];if(!level.solved[unlock]){toast('Giải hồ sơ tương ứng để mở loại vật liệu này.');return false;}if(e){toast('Thanh đã tồn tại. Tháo trước khi đổi vật liệu.');return false;}if(level.edges.length>=100){toast('Tối đa 100 thanh. Hãy tối ưu thiết kế.');return false;}const L=Bridge.length(A,B),mat=Bridge.materials[tool],m=Bridge.terrains[levelIndex];if(L>mat.max+.01){toast(`Thanh quá dài: tối đa ${mat.max}. Hãy chia bằng một điểm nối.`);return false;}if(L<15){toast('Hai điểm quá gần nhau.');return false;}if(Bridge.blocked(A,B,m)){toast('Thanh không được xuyên khối đá.');return false;}if(tool==='road'&&Math.abs(A.y-B.y)>Math.abs(A.x-B.x)*.72){toast('Mặt đường quá dốc. Hãy chia thành đoạn có độ dốc nhỏ hơn.');return false;}const price=L*mat.price;if(level.credits+.00001<price){toast('Chưa đủ vật liệu. Giải thêm toán hoặc tháo thanh thừa.');return false;}snapshot();level.edges.push({a,b,type:tool});audio.sfx('build');changed();return true;}
function removeNode(j){if(level.nodes[j]?.fixed)return toast('Không thể xóa neo cố định.');snapshot();level.nodes.splice(j,1);level.edges=level.edges.filter(e=>e.a!==j&&e.b!==j).map(e=>({...e,a:e.a>j?e.a-1:e.a,b:e.b>j?e.b-1:e.b}));selectedNode=null;changed();}
function removeAt(p){const e=findEdge(p);if(e>=0){if(level.edges[e].free)return toast('Không thể tháo đường có sẵn.');snapshot();level.edges.splice(e,1);changed();return;}const n=near(p);if(n>=0)removeNode(n);}
function findEdge(p){let best=-1,d=Math.max(10,9*1200/canvas.clientWidth);level.edges.forEach((e,i)=>{const a=level.nodes[e.a],b=level.nodes[e.b],L=Bridge.length(a,b),t=((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/(L*L);if(t<.1||t>.9)return;const z=Math.hypot(p.x-a.x-t*(b.x-a.x),p.y-a.y-t*(b.y-a.y));if(z<d){d=z;best=i;}});return best;}
function moveNode(j,p){const n=level.nodes[j],m=Bridge.terrains[levelIndex];if(n.fixed)return toast('Neo cố định không di chuyển được.');if(!Bridge.validPoint(p,m))return toast('Điểm mới nằm ngoài vùng xây.');if(level.nodes.some((v,k)=>k!==j&&Bridge.length(v,p)<15))return toast('Điểm quá gần nút khác.');const copy=level.nodes.map((v,k)=>k===j?{...v,...p}:v);for(const e of level.edges){if(Bridge.length(copy[e.a],copy[e.b])>Bridge.materials[e.type].max+.01||Bridge.blocked(copy[e.a],copy[e.b],m))return toast('Di chuyển này làm thanh quá dài hoặc xuyên đá.');}if(Bridge.cost(copy,level.edges)>100+180*level.solved.filter(Boolean).length)return toast('Không đủ vật liệu để kéo dài các thanh.');snapshot();level.nodes=copy;changed();}
$$('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;selectedNode=null;update();});$('connectBtn').onclick=()=>join(+$('nodeA').value,+$('nodeB').value);$('addNodeBtn').onclick=()=>{const x=+$('nodeX').value,y=+$('nodeY').value;if(Number.isFinite(x)&&Number.isFinite(y))addNode({x,y});};$('undoBtn').onclick=()=>{if(!level.history.length||running)return;const h=level.history.pop();level.nodes=h.nodes;level.edges=h.edges;selectedNode=null;changed();};$('clearBtn').onclick=()=>{if(confirm('Xóa bản thiết kế hiện tại? Câu toán, điểm kỷ lục vẫn giữ; vật liệu được hoàn lại.')){snapshot();level.nodes=Bridge.setup(levelIndex);level.edges=Bridge.freeEdges(levelIndex,level.nodes);selectedNode=null;changed();}};$('restoreBtn').onclick=()=>{if(!level.bestDesign)return;snapshot();level.nodes=structuredClone(level.bestDesign.nodes);level.edges=structuredClone(level.bestDesign.edges);level.powers.boost=level.bestDesign.boost;selectedNode=null;changed();};$('sampleBtn').onclick=()=>{if(!teacherTest)return;snapshot();const e=Bridge.example(levelIndex);level.nodes=e.nodes;level.edges=e.edges;level.solved.fill(true);level.score=400;changed();toast('Cầu minh họa để giáo viên thử. Không phải thiết kế bắt buộc.');};
const canvas=$('bridgeCanvas'),ctx=canvas.getContext('2d');function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1200/r.width,y:(e.clientY-r.top)*620/r.height};}function near(p){let nearest=-1,d=Math.max(13,13*1200/canvas.clientWidth);level.nodes.forEach((n,i)=>{const z=Bridge.length(n,p);if(z<d){d=z;nearest=i;}});return nearest;}
canvas.addEventListener('pointerdown',e=>{if(!level||running||level.energy<=0)return;audio.init();pointerStart=pos(e);dragFrom=near(pointerStart);dragPoint=pointerStart;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{hoverPoint=pos(e);if(pointerStart)dragPoint=hoverPoint;});canvas.addEventListener('pointerup',e=>{if(!pointerStart)return;const start=pointerStart,end=pos(e),from=dragFrom;pointerStart=null;dragFrom=null;dragPoint=null;const dragged=Bridge.length(start,end)>12;if(tool==='erase'){removeAt(end);return;}if(tool==='move'){if(dragged&&from>=0)moveNode(from,snapPoint(end));else toast('Kéo một điểm tự tạo đến vị trí mới.');return;}if(tool==='node'){addNode(snapPoint(end));return;}if(!level.solved[{road:0,steel:1,cable:2}[tool]])return toast('Mở vật liệu bằng cách hoàn thành hồ sơ toán trước.');if(dragged){let a=from>=0?from:addNode(snapPoint(start));if(a<0)return;let b=near(end);if(b<0)b=addNode(snapPoint(end));if(b>=0&&join(a,b))selectedNode=b;}else{let b=near(end);if(b<0)b=addNode(snapPoint(end));if(b<0)return;if(selectedNode===null)selectedNode=b;else if(selectedNode===b)selectedNode=null;else if(join(selectedNode,b))selectedNode=b;}update();});canvas.addEventListener('pointercancel',()=>{pointerStart=null;dragFrom=null;dragPoint=null;});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').open){selectedNode=null;update();}});
function inspectBridge(){return Bridge.route(level.nodes,level.edges,Bridge.terrains[levelIndex]);}
$('stopBtn').onclick=()=>{running=null;lastSimulation=null;update();toast('Đã dừng. Bạn có thể tiếp tục chỉnh cầu, không mất điểm.');};
$('runBtn').onclick=()=>{if(running||!level.solved.every(Boolean)||level.energy<=0)return;const path=inspectBridge();if(!path){toast('Chưa có đường xe chạy liên tục từ S đến F. Kiểm tra điểm nối và độ dốc.');$('algyText').textContent='Nối mặt đường từ S đến F. Đường chỉ giao nhau trên hình chưa tạo thành nút nối.';return;}selectedNode=null;failedState=null;lastSimulation=null;running={start:performance.now(),path,lastSolve:0,lastDistance:-80,distance:-80,checked:0};audio.init();update();};
function failRun(sim){failedState=sim;lastSimulation=sim;running=null;level.fails++;flashUntil=performance.now()+1500;audio.sfx('fail');persist();update();$('algyText').textContent=sim.reason;toast('Cần sửa cầu: '+sim.reason);}
function winRun(){running=null;const cost=spent(),points=Bridge.award(cost,level.score),old=level.bestScore||0,record=points.total>old;level.complete=true;const stars=points.build>=550?3:points.build>=300?2:1;level.stars=Math.max(level.stars,stars);if(record){level.bestScore=points.total;level.bestCost=cost;level.bestDesign={nodes:structuredClone(level.nodes),edges:structuredClone(level.edges),boost:level.powers.boost};}if(!teacherTest)save.unlocked=Math.max(save.unlocked,Math.min(5,levelIndex+1));persist();update();audio.sfx('win');modal(`<div class="center"><span class="eyebrow">${record?'KỶ LỤC MỚI':'CẦU ĐÃ VƯỢT THỬ NGHIỆM'}</span><h2 style="margin-top:15px">${points.total} điểm</h2><div class="resultStars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>Xe đã đến đích trên chính thiết kế của bạn.</p><div class="resultStats"><div><b>${level.score}</b><small>Điểm toán</small></div><div><b>${points.build}</b><small>Điểm tiết kiệm</small></div><div><b>${money(cost)}</b><small>Vật liệu thực dùng</small></div></div><p>Kỷ lục map: <b>${level.bestScore}</b> · ${teacherTest?'Lượt thử độc lập':`Tổng hành trình: <b>${totalBest()}</b> điểm`}</p><p class="smallprint">Thử lại không bị trừ điểm. Giảm vật liệu và chạy qua thành công để nâng kỷ lục; không cộng lặp các lượt chơi.</p><div class="quizActions"><button id="stayBuild">Tiếp tục tối ưu</button><button class="primary" id="nextMap">${levelIndex===5?'Về bản đồ':'Map tiếp theo →'}</button></div></div>`,'result');$('stayBuild').onclick=closeModal;$('nextMap').onclick=()=>{if(levelIndex===5){closeModal();goHome();}else startLevel(levelIndex+1,teacherTest);};}
function diagram(d){const c='#6fe8cf',cx=125,cy=86,R=62,r=d.r?R*d.r/d.R:27,n=d.n||90,a=-Math.PI/2,b=a+n*Math.PI/180,x=cx+R*Math.cos(b),y=cy+R*Math.sin(b);let shape='';if(d.type==='circle')shape=`<circle cx="${cx}" cy="${cy}" r="${R}" fill="#66d9cd13" stroke="${c}" stroke-width="3"/><path d="M${cx} ${cy}h${R}" stroke="${c}"/>`;else if(d.type==='ring'||d.type==='halfRing'){shape=`<circle cx="${cx}" cy="${cy}" r="${R}" fill="#6fe8cf40" stroke="${c}" stroke-width="2"/><circle cx="${cx}" cy="${cy}" r="${r}" fill="#15283b" stroke="${c}" stroke-width="2"/>`;if(d.type==='halfRing')shape+=`<rect x="60" y="${cy}" width="135" height="65" fill="#15283b"/><path d="M63 ${cy}h${62-r} M${cx+r} ${cy}H187" stroke="${c}"/>`;shape+=`<text x="220" y="80" fill="#dceaf8" font-size="15">R = ${d.hideR?'?':fmt(d.R)}</text><text x="220" y="104" fill="#dceaf8" font-size="15">r = ${d.hideInner?'?':fmt(d.r)}</text>`;}else{shape=`<circle cx="${cx}" cy="${cy}" r="${R}" fill="none" stroke="#42617b" stroke-dasharray="4 4"/><path d="M${cx} ${cy}L${cx} ${cy-R}A${R} ${R} 0 ${n>180?1:0} 1 ${x} ${y}Z" fill="#6fe8cf35" stroke="${c}" stroke-width="2"/><text x="220" y="100" fill="#dceaf8" font-size="15">n = ${d.hideN?'?':fmt(n)}°</text>`;}if(!['ring','halfRing'].includes(d.type))shape+=`<text x="220" y="73" fill="#dceaf8" font-size="15">R = ${d.hideR?'?':fmt(d.R)}</text>`;return `<svg class="mathFigure" viewBox="0 0 390 170" role="img" aria-label="Hình minh họa ${d.type==='circle'?'đường tròn':d.type.includes('Ring')||d.type==='ring'?'vành khuyên':'hình quạt'}"><text x="12" y="162" fill="#96aec2" font-size="10">Hình minh họa · đơn vị theo đề bài</text>${shape}<circle cx="${cx}" cy="${cy}" r="3" fill="#dffcf5"/><text x="${cx-18}" y="${cy+17}" fill="#dceaf8" font-size="12">O</text></svg>`;}
function openQuiz(i){if(running||level.energy<=0)return;const q=QUESTIONS[levelIndex][i];if(level.solved[i]){modal(`<span class="eyebrow">HỒ SƠ ${i+1} · ĐÃ HOÀN THÀNH</span><h3 style="margin-top:15px">${q.text}</h3>${diagram(q.diagram)}<div class="feedback success">${q.solution}</div><button id="reviewClose" style="margin-top:15px">Trở lại xây cầu</button>`,'review');$('reviewClose').onclick=closeModal;return;}modal(`<div class="quizTop"><span class="eyebrow">CHẾ TẠO ${i+1}/4</span><span id="quizTimer" class="timer"></span></div><div class="questionText">${q.text}</div>${diagram(q.diagram)}${q.options?`<div class="options">${q.options.map(a=>`<button data-answer="${a}">${fmt(a)} ${q.unit}</button>`).join('')}</div>`:`<form id="answerForm"><label for="answerInput">${q.unit.startsWith('π')?'Chỉ nhập hệ số đứng trước π (ví dụ: 2π → nhập 2).':'Nhập kết quả; chấp nhận dấu phẩy hoặc dấu chấm thập phân.'}</label><div class="answerRow"><input id="answerInput" type="text" inputmode="decimal" autocomplete="off" placeholder="Kết quả" aria-label="Kết quả"><span class="unit">${q.unit}</span><button class="primary" type="submit">Kiểm tra</button></div></form>`}<div id="quizFeedback" class="feedback" aria-live="polite"></div><div id="quizHint" class="hint"></div><div class="quizActions"><button id="hintBtn">Gợi ý (${level.hints})</button><button id="quizTimePower">+30 giây</button><button id="quizHealPower">Hồi năng lượng</button><button id="pauseQuiz">Lưu & về xưởng</button></div><p class="smallprint">Năng lượng: <span id="quizEnergy">${level.energy}</span>/100 · Sai hoặc hết giờ: −20. Thời gian còn lại được giữ khi về xưởng.</p>`,'quiz');quiz={i,last:performance.now(),hintUsed:false};updateTimer();$$('[data-answer]').forEach(b=>b.onclick=()=>checkAnswer(Number(b.dataset.answer)));if($('answerForm'))$('answerForm').onsubmit=e=>{e.preventDefault();const raw=$('answerInput').value.trim().replace(',','.');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw)){setFeedback('Hãy nhập một số hợp lệ, không kèm đơn vị.','error');return;}checkAnswer(Number(raw));};$('hintBtn').onclick=useHint;$('pauseQuiz').onclick=closeModal;$('quizTimePower').onclick=()=>power('time');$('quizHealPower').onclick=()=>power('heal');refreshQuizPowers();}
function refreshQuizPowers(){if(!quiz)return;$('quizTimePower').disabled=level.powers.time||settings.timer===0;$('quizHealPower').disabled=level.powers.heal||level.energy>=100;$('hintBtn').disabled=level.hints<=0||quiz.hintUsed;$('hintBtn').textContent=`Gợi ý (${level.hints})`;$('quizEnergy').textContent=level.energy;}
function setFeedback(t,type){if(!$('quizFeedback'))return;$('quizFeedback').textContent=t;$('quizFeedback').className='feedback '+type;}
function useHint(){if(!quiz||quiz.hintUsed||level.hints<=0)return;level.hints--;quiz.hintUsed=true;$('quizHint').textContent=QUESTIONS[levelIndex][quiz.i].hint;refreshQuizPowers();persist();}
function updateTimer(){if(!quiz)return;const t=level.times[quiz.i];$('quizTimer').textContent=settings.timer===0?'Không giới hạn':Math.ceil(t)+' giây';$('quizTimer').classList.toggle('low',settings.timer!==0&&t<=15);}
function checkAnswer(a){if(!quiz||level.energy<=0)return;const i=quiz.i,q=QUESTIONS[levelIndex][i];if(Math.abs(a-q.answer)<.00001){level.solved[i]=true;level.credits+=180;level.score+=100;level.correct++;if(levelIndex<2)scanUntil=performance.now()+30000;if(level.correct%2===0)level.hints++;audio.sfx('ok');quiz=null;persist();update();modal(`<div class="center"><span class="eyebrow">CHẾ TẠO THÀNH CÔNG</span><h2 style="margin:18px 0">+180 vật liệu <span style="color:var(--accent)">/ +100 điểm</span><div class="feedback success">${q.solution}</div><p style="margin-top:15px">${['Mặt đường đã mở. Tự đặt điểm và xây tuyến từ S đến F.','Hợp kim đã mở. Bạn có thể chống, tạo giàn hoặc kết hợp nhiều kiểu khung.','Cáp đã mở. Cáp chịu kéo tốt; thử treo mặt đường lên neo cao.','Đã đủ bốn hồ sơ. Hoàn thiện cầu rồi bấm Chạy thử.'][i]}</p><button id="backBuild" class="primary">Về xưởng xây cầu →</button></div>`,'correct');$('backBuild').onclick=closeModal;}else wrongAnswer(false);}
function wrongAnswer(timeout){if(!quiz)return;level.energy=Math.max(0,level.energy-20);level.wrong++;audio.sfx('fail');if(timeout)level.times[quiz.i]=settings.timer;setFeedback((timeout?'Hết thời gian.':'Kết quả chưa đúng.')+' −20 năng lượng. Kiểm tra công thức, đơn vị và dữ kiện rồi thử lại.','error');$('quizHint').textContent=QUESTIONS[levelIndex][quiz.i].hint;persist();update();if(level.energy===0){quiz=null;gameOver();}else{refreshQuizPowers();updateTimer();}}
function gameOver(){modal(`<div class="center"><span class="eyebrow">HẾT NĂNG LƯỢNG</span><h2 style="margin-top:20px">Nạp lại tinh thần kỹ sư!</h2><p>Chơi lại màn này với 100 năng lượng. Những màn đã mở vẫn được giữ.</p><button class="primary" id="replayBtn">Chơi lại màn</button><button id="overHome">Về bản đồ</button></div>`,'over');$('replayBtn').onclick=()=>{resetLevel();};$('overHome').onclick=()=>{closeModal();goHome();};}
function power(p){if(!level||running||level.powers[p]||level.energy<=0)return;if(p==='heal'){if(level.energy>=100)return toast('Năng lượng đang đầy.');level.energy=Math.min(100,level.energy+50);}else if(p==='time'){if(settings.timer===0)return toast('Đang tắt giới hạn thời gian.');const i=quiz?quiz.i:level.solved.findIndex(s=>!s);if(i<0)return;level.times[i]+=30;}else if(p==='scan'){scanUntil=performance.now()+12000;toast('Một thiết kế tham khảo hiện 12 giây. Bạn được tự do tạo cách khác, tiết kiệm hơn.');}else if(p==='boost')toast('Độ cứng kết cấu được tăng 30% trong màn này.');level.powers[p]=true;audio.sfx('build');persist();update();refreshQuizPowers();updateTimer();}
for(const p of ['heal','time','scan','boost'])$(p+'Btn').onclick=()=>power(p);
$('settingsBtn').onclick=()=>{modal(`<div class="modalHead"><span class="eyebrow">TÙY CHỈNH</span><h2>Âm thanh & hiển thị</h2></div><div class="settingsGrid"><label>Âm lượng: <b id="volumeValue">${Math.round(settings.volume*100)}%</b><input id="volumeSlider" type="range" min="0" max="100" value="${settings.volume*100}"></label><label><input id="muteCheck" type="checkbox" ${settings.muted?'checked':''}>Tắt âm thanh</label><label><input id="reduceCheck" type="checkbox" ${settings.reduced?'checked':''}>Giảm chuyển động trang trí</label><p class="smallprint">Mỗi màn có giai điệu riêng, được tạo trực tiếp trên thiết bị. Âm thanh bắt đầu sau thao tác đầu tiên.</p></div>`,'settings');$('volumeSlider').oninput=e=>{settings.volume=+e.target.value/100;$('volumeValue').textContent=e.target.value+'%';storeSettings();audio.init();};$('muteCheck').onchange=e=>{settings.muted=e.target.checked;storeSettings();};$('reduceCheck').onchange=e=>{settings.reduced=e.target.checked;storeSettings();};};
$('helpBtn').onclick=()=>modal(`<div class="modalHead"><span class="eyebrow">XƯỞNG TỰ DO · PHIÊN BẢN 2</span><h2>Xây theo cách của bạn</h2></div><ol class="helpList"><li><b>Giải 4 câu:</b> mở vật liệu và quyền chạy thử. Câu toán đúng được giữ khi sửa cầu.</li><li><b>Tạo đường S → F:</b> chọn Mặt đường, chạm điểm đầu rồi chạm vị trí trống để tạo điểm mới và nối. Tiếp tục chạm để xây liên tiếp. Mặt đường tối đa 180 đơn vị/thanh, không quá dốc.</li><li><b>Tự thiết kế kết cấu:</b> chọn Hợp kim (tối đa 340) hoặc Cáp (540). Được chống dưới, dựng giàn trên hoặc treo từ neo cao. Nút vuông vàng là neo cố định; điểm bạn đặt không tự trở thành neo.</li><li><b>Chỉnh sửa:</b> công cụ Điểm để đặt nút, Di chuyển để kéo nút, Tháo để chạm thanh hoặc điểm cần xóa. Thanh giao nhau chỉ liên kết khi có điểm nối chung. Có hoàn tác, xóa bản vẽ và khôi phục cầu đạt kỷ lục.</li><li><b>Thử và tối ưu:</b> xe tới đích an toàn là qua màn. Thử hỏng không trừ điểm. Bớt thanh thừa, đổi kết cấu rồi thử lại để tăng kỷ lục.</li></ol><div class="formula">Vật liệu = Σ (chiều dài × đơn giá)<br><small>Mặt đường: 0,32 · Hợp kim: 0,20 · Cáp: 0,11</small></div><p><b>Điểm tiết kiệm</b> = làm tròn[1000 × (1 − vật liệu dùng / 820)]. Chỉ ghi khi xe qua thành công. Điểm map = điểm toán + điểm tiết kiệm. Tổng hành trình = tổng kỷ lục tốt nhất của 6 map.</p><p class="smallprint">Sao theo điểm tiết kiệm: từ 550 = 3 sao; từ 300 = 2 sao; còn lại = 1 sao. Tháo thanh hoàn đủ vật liệu; chia nhỏ một thanh không làm rẻ hơn. Mô phỏng đàn hồi 2D đơn giản hóa dành cho game, không dùng thiết kế công trình thật.</p><p class="smallprint">Điện thoại: xoay ngang hoặc dùng thanh phóng to. Có thể nhập tọa độ và chọn điểm bằng bàn phím ở dưới xưởng. Phím Esc bỏ điểm đang chọn.</p>`,'help');
$('fullBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('Trình duyệt chưa hỗ trợ toàn màn hình.'));};
$('teacherBtn').onclick=requestTeacherAccess;
function requestTeacherAccess(){
 teacherAuthorized=false;
 modal(`<div class="modalHead"><span class="eyebrow">KHU VỰC GIÁO VIÊN</span><h2>Nhập mật khẩu giáo viên</h2><p>Nhập mật khẩu để xem đáp án, điều chỉnh thời gian và chơi thử từng màn.</p></div><form id="teacherLoginForm"><label for="teacherPassword">Mật khẩu</label><input id="teacherPassword" type="password" inputmode="numeric" autocomplete="off" required maxlength="64" style="width:100%;margin:8px 0 12px" aria-describedby="teacherLoginError"><div id="teacherLoginError" class="feedback" role="alert"></div><div class="quizActions"><button type="button" id="cancelTeacherLogin">Hủy</button><button type="submit" class="primary">Mở chế độ giáo viên</button></div></form>`,'teacherLogin');
 $('teacherPassword').focus();
 $('cancelTeacherLogin').onclick=closeModal;
 $('teacherLoginForm').onsubmit=e=>{e.preventDefault();if($('teacherPassword').value!==TEACHER_PASSWORD){$('teacherLoginError').textContent='Mật khẩu chưa đúng. Vui lòng nhập lại.';$('teacherLoginError').className='feedback error';$('teacherPassword').value='';$('teacherPassword').focus();return;}teacherAuthorized=true;openTeacher(teacherIndex);};
}

function openTeacher(i){if(!teacherAuthorized){requestTeacherAccess();return;}teacherIndex=i;modal(`<div class="modalHead"><span class="eyebrow">KHU VỰC GIÁO VIÊN</span><h2>Ngân hàng 24 câu & thử màn</h2><p>Nội dung hiển thị đúng như chế độ học sinh. Chơi thử độc lập với tiến độ đã lưu.</p></div><label for="teacherMapSelect">Chọn công trình</label><div class="teacherMap"><select id="teacherMapSelect">${MAPS.map((m,j)=>`<option value="${j}" ${j===i?'selected':''}>${j+1}. ${m.name}</option>`).join('')}</select><button id="testMap" class="primary">Chơi thử màn này</button></div><label>Thời gian mỗi câu (áp dụng cho màn mới / chơi thử)<select id="teacherTimer"><option value="0">Không giới hạn</option>${[30,60,90,120,180].map(t=>`<option value="${t}" ${settings.timer===t?'selected':''}>${t} giây</option>`).join('')}</select></label><div id="teacherQuestions">${QUESTIONS[i].map((q,j)=>`<div class="teacherQuestion"><p><b>Câu ${j+1}.</b> ${q.text}</p><details><summary>Xem đáp án & lời giải</summary><div class="solution">${q.solution}</div></details></div>`).join('')}</div><button id="exportBtn">Xuất kết quả cá nhân (CSV)</button><p class="smallprint">Dữ liệu chỉ lưu trên trình duyệt hiện tại. Đóng cửa sổ sẽ khóa lại khu vực giáo viên.</p>`,'teacher');$('teacherTimer').value=settings.timer;$('teacherTimer').onchange=e=>{settings.timer=+e.target.value;storeSettings();};$('teacherMapSelect').onchange=e=>openTeacher(+e.target.value);$('testMap').onclick=()=>{if(running)return toast('Đợi lượt chạy thử kết thúc trước khi đổi màn.');if(level&&!teacherTest)persist();startLevel(i,true);};$('exportBtn').onclick=()=>{const rows=[['Tên','Màn','Câu đúng','Điểm toán','Lần sai','Lần thử hỏng','Sao','Kỷ lục điểm','Vật liệu kỷ lục'],...save.levels.map((l,j)=>[save.name,j+1,l.solved.filter(Boolean).length,l.score,l.wrong,l.fails,l.stars,l.bestScore||0,l.bestCost??''])],csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download='KetQua_CauNoiKhongGian.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
function poly(c,points,fill,stroke,width=1){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
function line(c,x1,y1,x2,y2,color,w=2){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.strokeStyle=color;c.lineWidth=w;c.stroke();}
function island(c,x,y,w,h,color,flip=false){poly(c,[[x,y],[x+w*.35,y-17],[x+w,y],[x+w*.86,y+h*.35],[x+w*.57,y+h],[x+w*.24,y+h*.7]],'#203b4c');poly(c,[[x,y],[x+w*.35,y-17],[x+w,y],[x+w*.8,y+23],[x+w*.18,y+25]],color);poly(c,[[x+w*.18,y+25],[x+w*.57,y+h],[x+w*.24,y+h*.7]],'#142d42');line(c,x+w*.5,y+40,x+w*.58,y+h*.78,'#376c78',3);}
function vehicle(c,x,y,color,t,scale=1){c.save();c.translate(x,y);c.scale(scale,scale);c.shadowColor=color;c.shadowBlur=16;poly(c,[[-31,-15],[-23,-34],[9,-34],[24,-20],[37,-16],[36,-4],[-33,-4]],color);c.shadowBlur=0;poly(c,[[-15,-30],[5,-30],[16,-20],[-19,-20]],'#17314a');c.fillStyle='#effff8';c.fillRect(30,-16,7,5);c.fillStyle='#e16d81';c.fillRect(-33,-15,4,5);for(const wx of [-20,23]){c.beginPath();c.arc(wx,-3,9,0,Math.PI*2);c.fillStyle='#0a1524';c.fill();c.beginPath();c.arc(wx,-3,5,0,Math.PI*2);c.fillStyle='#6e8794';c.fill();line(c,wx+4*Math.cos(t),-3+4*Math.sin(t),wx-4*Math.cos(t),-3-4*Math.sin(t),'#c4e8e6',2);}c.restore();}
function robot(c,x,y,t,col){c.save();c.translate(x,y+Math.sin(t)*2);c.fillStyle='#d4e8ec';c.fillRect(-10,-26,20,20);c.fillStyle='#244853';c.fillRect(-8,-23,16,9);c.fillStyle=col;c.fillRect(-5,-20,3,3);c.fillRect(3,-20,3,3);c.fillStyle='#7598a6';c.fillRect(-8,-4,6,9);c.fillRect(2,-4,6,9);line(c,0,-26,0,-34,col,2);c.beginPath();c.arc(0,-35,3,0,7);c.fillStyle=col;c.fill();c.restore();}
function scenery(c,w,h,m,t){const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0a1329');g.addColorStop(.65,m.sky);g.addColorStop(1,'#102337');c.fillStyle=g;c.fillRect(0,0,w,h);for(let i=0;i<75;i++){const x=(i*167+73)%1200,y=(i*i*29+17)%450;c.globalAlpha=.25+.45*(.5+.5*Math.sin(t*.3+i));c.fillStyle='#d9f1ff';c.fillRect(x,y,i%7===0?2:1,i%7===0?2:1);}c.globalAlpha=1;const pg=c.createRadialGradient(840,95,5,880,110,100);pg.addColorStop(0,m.planet);pg.addColorStop(1,m.sky);c.fillStyle=pg;c.beginPath();c.arc(865,110,73,0,7);c.fill();c.strokeStyle=m.color+'44';c.lineWidth=2;c.beginPath();c.ellipse(865,110,117,25,-.3,0,7);c.stroke();for(let k=0;k<3;k++){c.strokeStyle=m.color+'0c';c.lineWidth=18;c.beginPath();c.moveTo(0,80+k*40);c.bezierCurveTo(300,150+Math.sin(t*.2)*40,600,10+k*60,1200,170+k*20);c.stroke();}environment(c,m,t);island(c,50,485,170,90,'#336370');island(c,1020,460,130,85,'#30586a');poly(c,[[0,620],[180,510],[400,580],[650,530],[850,580],[1200,490],[1200,620]],'#102337');}
function environment(c,m,t){const idx=MAPS.indexOf(m);c.save();c.globalAlpha=.35;if(idx===0){for(let i=0;i<5;i++){line(c,70+i*33,280,70+i*33,240-i%2*20,'#7af1bd',3);poly(c,[[50+i*33,252],[70+i*33,210-i%2*20],[89+i*33,252]],'#5caa91');}}else if(idx===1){for(let i=0;i<5;i++)poly(c,[[30+i*240,290],[80+i*235,130+i%2*50],[170+i*230,310]],'#e0a86b');}else if(idx===2){for(let i=0;i<6;i++){c.fillStyle='#bd9ffc';c.beginPath();c.ellipse(80+i*200,215+Math.sin(t+i)*8,30,8,-.4,0,7);c.fill();line(c,80+i*200,215,80+i*200,285,'#ad9bec',2);}}else if(idx===3){c.strokeStyle='#86dfff';c.lineWidth=5;c.beginPath();c.ellipse(590,160,195,65,-.2,0,7);c.stroke();for(let i=0;i<4;i++)poly(c,[[i*350,280],[30+i*340,190],[70+i*340,280]],'#99d5ec');}else if(idx===4){for(let j=0;j<6;j++){c.strokeStyle=['#7de4c7','#d88cf8','#95b0ff'][j%3];c.lineWidth=7;c.beginPath();c.moveTo(0,70+j*18);c.bezierCurveTo(350,170+Math.sin(t+j)*15,750,20,1200,160+j*10);c.stroke();}}else{c.strokeStyle='#ffe09a';c.lineWidth=9;c.beginPath();c.ellipse(1090,185,55,100,0,0,7);c.stroke();for(let i=0;i<7;i++){c.fillStyle='#ffe09a';c.fillRect(490+i*20,150+Math.sin(t+i)*8,4,4);}}c.restore();}
function drawBridge(now){if(!level)return;const map=Bridge.terrains[levelIndex],m=MAPS[levelIndex],t=settings.reduced?0:now/1000;scenery(ctx,1200,620,m,t);
 // Each level has different banks, platforms, supports and solid obstacles.
 island(ctx,-110,map.start[1]+7,map.start[0]+110,245,'#397b76');island(ctx,map.end[0],map.end[1]+7,1310-map.end[0],245,'#386e79');line(ctx,0,map.start[1],map.start[0],map.start[1],'#d8efde',9);line(ctx,map.end[0],map.end[1],1200,map.end[1],'#d8efde',9);
 for(const p of map.platforms){poly(ctx,[[p.x-12,p.y+6],[p.x+p.w+12,p.y+6],[p.x+p.w-12,580],[p.x+18,580]],'#305365');line(ctx,p.x,p.y,p.x+p.w,p.y,'#d8efde',11);}
 for(const r of map.obstacles){poly(ctx,[[r.x,r.y+20],[r.x+20,r.y],[r.x+r.w-18,r.y],[r.x+r.w,r.y+20],[r.x+r.w,r.y+r.h],[r.x,r.y+r.h]],'#76605d','#b1937c',2);ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();for(let k=-r.h;k<r.w+r.h;k+=22)line(ctx,r.x+k,r.y,r.x+k+r.h,r.y+r.h,'#e0c39820',6);ctx.restore();}
 for(const a of map.anchors){if(map.platforms.some(p=>a[0]>=p.x&&a[0]<=p.x+p.w))continue;line(ctx,a[0],a[1]+9,a[0],610,'#43667580',10);ctx.fillStyle='#2a5360';ctx.fillRect(a[0]-17,a[1]+5,34,15);}
 robot(ctx,map.start[0]-85,map.start[1]-12,t,COLORS[save.avatar]);line(ctx,map.end[0]+60,map.end[1],map.end[0]+60,map.end[1]-65,m.color,3);poly(ctx,[[map.end[0]+60,map.end[1]-65],[map.end[0]+99,map.end[1]-52],[map.end[0]+60,map.end[1]-40]],m.color);
 if(!running&&$('snapCheck').checked){ctx.fillStyle='#9acbdd20';for(let x=Math.ceil(map.start[0]/20)*20;x<=map.end[0];x+=20)for(let y=100;y<=540;y+=20)if(!map.obstacles.some(r=>Bridge.inside({x,y},r)))ctx.fillRect(x,y,1.5,1.5);}
 if(scanUntil>now){const ex=Bridge.example(levelIndex);ctx.setLineDash([7,9]);ex.edges.forEach(e=>line(ctx,ex.nodes[e.a].x,ex.nodes[e.a].y,ex.nodes[e.b].x,ex.nodes[e.b].y,m.color+'66',2));ctx.setLineDash([]);}
 if(running){const end=running.path.total+(map.convoy-1)*110+65,target=Math.min(end,(now-running.start)*.08-80);running.distance=target; // Check all intermediate loads, even on a slow device.
 if(now-running.lastSolve>80||target>=end){running.lastSolve=now;let d=running.lastDistance;while(d<target&&running){d=Math.min(target,d+16);const sim=Bridge.simulate(level.nodes,level.edges,map,running.path,d,level.powers.boost);lastSimulation=sim;running.lastDistance=d;if(!sim.ok){failRun(sim);break;}}if(running&&target>=end)winRun();}
 }
 const sim=lastSimulation,u=sim?.displacements||[],nodes=level.nodes;const deformed=(n,i)=>({x:n.x+Math.max(-65,Math.min(65,u[3*i]||0)),y:n.y+Math.max(-65,Math.min(65,u[3*i+1]||0))});
 for(let j=0;j<level.edges.length;j++){const e=level.edges[j],a=deformed(nodes[e.a],e.a),b=deformed(nodes[e.b],e.b),stress=sim?.stress?.[j]||0;let col=e.free?'#d4ebde':e.type==='road'?'#dcf7e7':e.type==='steel'?'#87bdcf':'#f0c979';if(running||failedState){if(stress>.8)col='#ff8290';else if(stress>.5)col='#ffd879';}ctx.shadowColor=e.type==='road'?m.color:'#0000';ctx.shadowBlur=e.type==='road'?5:0;ctx.lineWidth=e.type==='road'?9:e.type==='steel'?5:2.8;ctx.strokeStyle=col;ctx.beginPath();ctx.moveTo(a.x,a.y);if(e.type==='cable'){const sag=(!sim||stress<.0001)?7:1;ctx.quadraticCurveTo((a.x+b.x)/2,(a.y+b.y)/2+sag,b.x,b.y);}else{const dx=b.x-a.x,dy=b.y-a.y,L=Bridge.length(a,b),r1=Math.max(-.3,Math.min(.3,u[e.a*3+2]||0)),r2=Math.max(-.3,Math.min(.3,u[e.b*3+2]||0));ctx.bezierCurveTo(a.x+dx/3-dy/L*r1*L/3,a.y+dy/3+dx/L*r1*L/3,b.x-dx/3+dy/L*r2*L/3,b.y-dy/3-dx/L*r2*L/3,b.x,b.y);}ctx.stroke();ctx.shadowBlur=0;}
 const rad=Math.max(7,4.7*1200/canvas.clientWidth),font=Math.max(12,10*1200/canvas.clientWidth);nodes.forEach((n,i)=>{const p=deformed(n,i),sel=selectedNode===i||dragFrom===i;ctx.fillStyle=sel?m.color:n.fixed?'#ffd784':'#142b3b';ctx.strokeStyle=n.fixed?'#fff0b7':sel?'#ecffff':'#9bccd6';ctx.lineWidth=2;if(n.fixed){ctx.fillRect(p.x-rad,p.y-rad,rad*2,rad*2);ctx.strokeRect(p.x-rad,p.y-rad,rad*2,rad*2);}else{ctx.beginPath();ctx.arc(p.x,p.y,sel?rad*1.25:rad,0,7);ctx.fill();ctx.stroke();}if(!running){ctx.font=font+'px system-ui';ctx.textAlign='center';ctx.fillStyle='#dbeaf4';ctx.fillText(n.label,p.x,p.y-rad-6);ctx.textAlign='left';}});
 if(pointerStart&&dragPoint&&tool!=='erase'){const a=dragFrom>=0?nodes[dragFrom]:snapPoint(pointerStart);line(ctx,a.x,a.y,dragPoint.x,dragPoint.y,m.color,3);}else if(selectedNode!==null&&hoverPoint&&!running){const a=nodes[selectedNode];if(a){ctx.setLineDash([6,8]);line(ctx,a.x,a.y,hoverPoint.x,hoverPoint.y,m.color+'88',2);ctx.setLineDash([]);}}
 const carAt=(d,path)=>{if(d<0)return{x:map.start[0]+d,y:map.start[1],angle:0};if(d>path.total)return{x:map.end[0]+d-path.total,y:map.end[1],angle:0};const q=Bridge.locate(path,d),a=deformed(nodes[q.a],q.a),b=deformed(nodes[q.b],q.b);return{x:a.x+(b.x-a.x)*q.u,y:a.y+(b.y-a.y)*q.u,angle:Math.atan2(b.y-a.y,b.x-a.x)};};
 if(running){for(let j=0;j<map.convoy;j++){const p=carAt(running.distance-j*110,running.path);ctx.save();ctx.translate(p.x,p.y-6);ctx.rotate(p.angle);vehicle(ctx,0,0,j===0?COLORS[save.avatar]:j===1?'#ffd18c':'#c5acff',t*8,.85);ctx.restore();}}else vehicle(ctx,map.start[0]-55,map.start[1]-6,COLORS[save.avatar],0,.85);
 if(failedState&&now<flashUntil&&!settings.reduced){const i=failedState.critical>=0?failedState.critical:0,p=deformed(nodes[i],i),age=(1500-(flashUntil-now))/1000;for(let k=0;k<12;k++){ctx.fillStyle='#ffaf92';ctx.fillRect(p.x+Math.cos(k*2.4)*age*50,p.y+Math.sin(k*2.1)*age*40+age*age*50,4,4);}}
 $('stressText').textContent=running||failedState?`Độ võng: ${money(Math.min(999,sim?.maxDisp||0))} / 32 · Tải cao nhất: ${Math.round(Math.min(9.99,sim?.maxStress||0)*100)}%`:'Chưa thử tải · Không bắt buộc mẫu cầu';
}
function drawHero(now){const c=$('heroCanvas').getContext('2d'),t=settings.reduced?0:now/1000;c.clearRect(0,0,900,700);c.save();c.translate(5,0);for(let i=0;i<45;i++){c.fillStyle=i%3?'#a4cfe44d':'#dcffef';c.fillRect((i*173)%860,50+(i*i*29)%560,2,2);}const g=c.createRadialGradient(505,290,10,505,290,260);g.addColorStop(0,'#59dbbb1c');g.addColorStop(1,'#59dbbb00');c.fillStyle=g;c.fillRect(100,20,780,620);c.strokeStyle='#88dcd530';c.lineWidth=1;c.beginPath();c.ellipse(490,315,300,185,-.25,0,7);c.stroke();c.fillStyle='#73a9a780';c.beginPath();c.arc(625,150,64,0,7);c.fill();c.strokeStyle='#a1cfbd44';c.beginPath();c.ellipse(625,150,98,17,-.3,0,7);c.stroke();const bob=Math.sin(t*.6)*5;c.translate(0,bob);island(c,65,360,210,210,'#397d73');island(c,625,305,220,230,'#316c67');const a=[260,349],b=[645,294];for(let j=0;j<4;j++){const x1=a[0]+(b[0]-a[0])*j/4,y1=a[1]+(b[1]-a[1])*j/4,x2=a[0]+(b[0]-a[0])*(j+1)/4,y2=a[1]+(b[1]-a[1])*(j+1)/4;line(c,x1,y1,x2,y2,'#b0e8d5',9);line(c,x1,y1,(x1+x2)/2,(y1+y2)/2+85,'#589fa2',5);line(c,x2,y2,(x1+x2)/2,(y1+y2)/2+85,'#589fa2',5);}line(c,305,427,592,386,'#427480',4);robot(c,165,338,t,COLORS[save.avatar]);const p=settings.reduced?.45:(t*.045)%1;vehicle(c,280+p*345,335-p*49,'#e5bc70',t*4,1.15);c.restore();}
function frame(now){const dt=lastFrame?Math.min((now-lastFrame)/1000,.2):0;lastFrame=now;if(!document.hidden){if($('game').classList.contains('hidden'))drawHero(now);else drawBridge(now);if(quiz&&$('modal').open&&settings.timer!==0){level.times[quiz.i]=Math.max(0,level.times[quiz.i]-dt);updateTimer();if(level.times[quiz.i]<=0)wrongAnswer(true);}}requestAnimationFrame(frame);}
window.addEventListener('beforeunload',()=>persist());document.addEventListener('visibilitychange',()=>{if(document.hidden){persist();if(running)running.pausedAt=performance.now();}else{lastFrame=performance.now();if(running?.pausedAt){running.start+=performance.now()-running.pausedAt;delete running.pausedAt;}}});setInterval(()=>{if(level&&!teacherTest)persist();},5000);storeSettings();renderHome();requestAnimationFrame(frame);
$('zoomSlider').oninput=e=>{canvas.style.width=(+e.target.value*100)+'%';};
